Build: Port to 1.19.3 fabric
EssentialGG/UniversalCraft pull request #43
Opened 2022-11-27 23:25 UTC by DJtheRedstoner

Should be mostly functional, marked as draft until more extensive testing is done.

2022-12-02 02:39 UTC, DJtheRedstoner commented
This is now ready for review.

2022-12-02 08:40 UTC, cbyrneee approved these changes
It all looks good to me from a code standpoint, I assume that you've gone through and checked that everything functions as expected. 

I don't see any issues with it other than `UKeyboard#allowRepeatEvents`. Can we not do:
```kt
//#if MC >= 11903
//$$ @Deprecated("Repeat keyboard events are always enabled in 1.19.3+")
//#endif
@JvmStatic
fun allowRepeatEvents(enabled: Boolean) {
```

Otherwise, someone won't be aware of the fact that they're always enabled on 1.19.3 and can't be disabled, probably causing someone a headache for 30 minutes until they check the UniversalCraft source.

2022-12-02 18:36 UTC, Sk1er requested changes

2022-12-02 18:36 UTC, Sk1er commented on src/main/kotlin/gg/essential/universal/UKeyboard.kt
> +        //$$ // Minecraft removed this function in 1.19.3, repeat events are now always enabled.
Should throw this in a KDoc on the function as well

2022-12-03 22:13 UTC, DJtheRedstoner commented
> I don't see any issues with it other than `UKeyboard#allowRepeatEvents`. Can we not do:
> 
> ```kotlin
> //#if MC >= 11903
> //$$ @Deprecated("Repeat keyboard events are always enabled in 1.19.3+")
> //#endif
> @JvmStatic
> fun allowRepeatEvents(enabled: Boolean) {
> ```
> 
> Otherwise, someone won't be aware of the fact that they're always enabled on 1.19.3 and can't be disabled, probably causing someone a headache for 30 minutes until they check the UniversalCraft source.

While this is an option, I'm not sure that deprecating the method really solve the issue. If it's deprecated on all versions, users will probably just ignore it or suppress the warning. If it's only deprecated on 1.19.3+, it is easy to miss the warning unless that version is your main version.

I've done what I think is a good compromise and added the note to the method kdoc, so it shows up as part of the method documentation and not just as part of the implementation.

Finally, before making this change I [searched GitHub](https://github.com/search?q=allowRepeatEvents&type=code) for users of this method, and as far as I can tell it's only used to opt-in to repeat events, not opt out. All Elementa guis [opt-in by default](https://github.com/EssentialGG/Elementa/blob/0799a87d607293c569635348e4e87b04eb6be974/src/main/kotlin/gg/essential/elementa/WindowScreen.kt#L20), and I [can't find](https://github.com/search?q=enableRepeatKeys&type=code) any notable examples on github that opt-out of this Elementa behavior.

2022-12-03 22:54 UTC, cbyrneee approved these changes

2022-12-08 00:04 UTC, merged